name: CapRover

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up npm
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install caprover
        run: npm install -g caprover

      - name: Caprover Deploy
        run: caprover deploy -h '${{ secrets.CAPROVER_HOST }}' -p '${{ secrets.CAPROVER_PASSWORD }}' -b 'main' -a 'audnexus'
