name: 'jest-coverage'
on:
  pull_request:
    branches:
      - main
jobs:
  coverage:
    env:
      ADP_TOKEN: ${{ secrets.ADP_TOKEN }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
          package-manager: pnpm
          github-token: ${{ secrets.GITHUB_TOKEN }}
          #   threshold: 80 # optional parameter